#  MIT License
#
#  Copyright (c) 2021 Vilius Sutkus <ViliusSutkus89@gmail.com>
#
#  https://github.com/ViliusSutkus89/Sample_Android_Library-MavenCentral-Instrumented_Tests
#  .github/workflows/appRelease.yml - v1.3.0
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
#
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#  SOFTWARE.

name: appRelease
on: workflow_dispatch

permissions:
  actions: none
  checks: none
  contents: none
  deployments: none
  issues: none
  packages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  buildApplication:
    environment: SampleAppKeystore
    runs-on: ubuntu-20.04
    outputs:
      # in case there's a commit between buildSampleApp and releaseApp jobs...
      GIT_TAG: ${{ github.event.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.ref }}

      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 11
      - uses: android-actions/setup-android@v2

      - id: decodeAppKeystore
        run: |
          echo "${{ env.APP_SIGNING_KEYFILE_BASE64 }}" | base64 --decode - > "$HOME/com.viliussutkus89.pdf2htmlex.application.jks"
          echo "::set-output name=APP_SIGNING_KEYFILE::$HOME/com.viliussutkus89.pdf2htmlex.application.jks"
        env:
          APP_SIGNING_KEYFILE_BASE64: ${{ secrets.APP_SIGNING_KEYFILE_BASE64 }}

      - run: ./gradlew build lintRelease
        working-directory: application
        env:
          APP_SIGNING_KEYFILE: ${{ steps.decodeAppKeystore.outputs.APP_SIGNING_KEYFILE }}
          APP_SIGNING_PASS: ${{ secrets.APP_SIGNING_PASS }}
          APP_SIGNING_ALIAS: ${{ secrets.APP_SIGNING_ALIAS }}

      - uses: actions/upload-artifact@v2
        with:
          name: APKs
          path: application/app/build/outputs/apk/**/*.apk

      - run: mv application/app/build/reports/lint-results-release.html application-lint-report.html
      - uses: actions/upload-artifact@v2
        with:
          name: application-lint-report.html
          path: application-lint-report.html

  releaseApp:
    needs: buildApplication
    permissions:
      # Permission needed to create the GitHub release.
      contents: write
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
#           A branch is required for post release version increment commit
          ref: ${{ needs.buildSampleApp.outputs.GIT_TAG }}

      - uses: actions/download-artifact@v2
        with:
          path: artifacts

      - run: ./ci-scripts/getVersion --ci
        id: version

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "appRelease-v${{ steps.version.outputs.appVersion }}"
          name: "[AppRelease] ${{ github.event.repository.name }} v${{ steps.version.outputs.appVersion }}"
          artifacts: "artifacts/APKs/**/*.apk,artifacts/application-lint-report.html/application-lint-report.html"

      - run: ./ci-scripts/incrementVersion --application
        id: postReleaseVersionIncrement

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Post release app version increment to ${{ steps.postReleaseVersionIncrement.outputs.newAppVersion }} (from ${{ steps.postReleaseVersionIncrement.outputs.oldAppVersion }})"
          file_pattern: ${{ steps.postReleaseVersionIncrement.outputs.files }}
